### ISSUE TITLE
Please can you help me by clarifying that if it will work on a Ubuntu machine.

### ISSUE THREAD

**Issue by Dessant56** [Nirj2004/WhatsApp-SpammerBot#1]
I'm currently confused. Can you please tell me that if this code will run on my Ubuntu laptop.
Thank you 💕😊💕💕💕💕😊😊💕.
Please reply fast urgent.

**Comment by Nirj2004** [comment]
Sure.
Most of the Python scripts will work on any Linux Distributions(including Ubuntu).
If you are still facing problem, please try updating python version
`sudo pip install python3`
If it still doesnot work, please share the error message.

KEEP CODING!!!
