### ISSUE TITLE
Sir I am unable to contribute.

### ISSUE THREAD

**Issue by Dessant56** [Nirj2004/WhatsApp-SpammerBot#3]
Sir I am unable to contribute as I am having some problems with my UPI applications. I'm very sorry for that. Can you please help me solve the problem with my UPI app, my app is Paytm and Phone Pe. Please HELP 🥺🥺🥺

**Comment by Nirj2004** [comment]
Ok, If you face any problem don't worry. It's ok i can understand and also, it is not compulsory to contribute.


KEEP CODING!!!
